print("INPUT")
print("------")
n1=int(input('enter  first integer:'))
n2=int(input('enter second integer:'))
n3=int(input('enter  third integer:'))
print("\n")
f1=float(input('enter  First Float:'))
f2=float(input('enter  Second Float:'))
f3=float(input('enter  Third Float:'))
print("\n")
s1=input('Enter First String:')
s2=input('Enter Second String:')
print("\n")
c=complex(input('Enter Complex Number:'))
print("\n")
print('OUPUT')
print("------")
print('First Integer:',n1)
print('Second Integer:',n2)
print('Third Integer:',n3)
print("\n")
print('First Float:',f1)
print('Second Float:',f2)
print('Third Float:',f3)
print("\n")
print('First String:'+s1)
print('Second String:'+s2)
print("\n")
print('Complex Number:',c)
